export const EVOPOOL_ABI = [
  "function getReserves() view returns (uint256, uint256)",
  "function feeBps() view returns (uint256)",
  "function curveBeta() view returns (uint256)",
  "function curveMode() view returns (uint8)",
  "function tradeCount() view returns (uint256)",
  "function cumulativeVolume0() view returns (uint256)",
  "function cumulativeVolume1() view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function swap(bool zeroForOne, uint256 amountIn, uint256 minAmountOut) returns (uint256)",
  "function addLiquidity(uint256 amount0, uint256 amount1) returns (uint256)",
  "function removeLiquidity(uint256 liquidity) returns (uint256, uint256)",
  "function token0() view returns (address)",
  "function token1() view returns (address)",
  "function reserve0() view returns (uint256)",
  "function reserve1() view returns (uint256)",
  "function MAX_FEE_BPS() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function approve(address, uint256) returns (bool)",
  "function allowance(address, address) view returns (uint256)",
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function transfer(address, uint256) returns (bool)",
  "function price0CumulativeLast() view returns (uint256)",
  "function price1CumulativeLast() view returns (uint256)",
  "function blockTimestampLast() view returns (uint32)",
  "function protocolFeeBps() view returns (uint256)",
  "function protocolFeeAccum0() view returns (uint256)",
  "function protocolFeeAccum1() view returns (uint256)",
  "function treasury() view returns (address)",
  "function parameterUpdateBlock() view returns (uint256)",
  "function epochManager() view returns (address)",
  "function paused() view returns (bool)",
  "event Swap(address indexed sender, bool zeroForOne, uint256 amountIn, uint256 amountOut, uint256 feeAmount)",
  "event LiquidityAdded(address indexed provider, uint256 amount0, uint256 amount1, uint256 liquidity)",
  "event LiquidityRemoved(address indexed provider, uint256 amount0, uint256 amount1, uint256 liquidity)",
  "event ParametersUpdated(uint256 newFeeBps, uint256 newCurveBeta, uint8 newMode, address indexed agent)",
  "event ProtocolFeeCollected(address indexed treasury, uint256 amount0, uint256 amount1)",
] as const;

export const CONTROLLER_ABI = [
  "function registerAgent() payable",
  "function deregisterAgent()",
  "function topUpBond() payable",
  "function depositTokenBond(uint256 amount)",
  "function withdrawTokenBond()",
  "function submitParameterUpdate(uint256 newFeeBps, uint256 newCurveBeta, uint8 newCurveMode)",
  "function getAgentInfo(address) view returns (tuple(address agentAddress, uint256 bondAmount, uint256 tokenBondAmount, uint256 registeredAt, uint256 lastUpdateTime, bool active))",
  "function getAgentCount() view returns (uint256)",
  "function agentList(uint256) view returns (address)",
  "function updateCount(address) view returns (uint256)",
  "function cooldownSeconds() view returns (uint256)",
  "function minBond() view returns (uint256)",
  "function maxFeeDelta() view returns (uint256)",
  "function maxBetaDelta() view returns (uint256)",
  "function paused() view returns (bool)",
  "function pool() view returns (address)",
  "function bondToken() view returns (address)",
  "event AgentRegistered(address indexed agent, uint256 bondAmount)",
  "event AgentDeregistered(address indexed agent, uint256 bondReturned)",
  "event BondTopUp(address indexed agent, uint256 amount, uint256 newTotal)",
  "event TokenBondDeposited(address indexed agent, uint256 amount, uint256 newTotal)",
  "event AgentUpdateProposed(address indexed agent, uint256 newFeeBps, uint256 newCurveBeta, uint8 newCurveMode, uint256 timestamp)",
  "event AgentSlashed(address indexed agent, uint256 slashAmount, string reason)",
] as const;

export const EPOCH_MANAGER_ABI = [
  "function currentEpochId() view returns (uint256)",
  "function epochDuration() view returns (uint256)",
  "function epochRewardAmount() view returns (uint256)",
  "function getEpochProposals(uint256) view returns (tuple(address agent, uint256 feeBps, uint256 curveBeta, uint8 curveMode, uint256 timestamp)[])",
  "function getEpochAgents(uint256) view returns (address[])",
  "function epochs(uint256) view returns (uint256 epochId, uint256 startTime, uint256 endTime, address winner, uint256 winnerScore, uint256 proposalCount, bool finalized)",
  "function getAgentStats(address) view returns (uint256 totalScore, uint256 epochsWon, uint256 epochsParticipated)",
  "function getTimeRemaining() view returns (uint256)",
  "function submitProposal(uint256 feeBps, uint256 curveBeta, uint8 curveMode)",
  "function claimReward(uint256 epochId)",
  "event EpochStarted(uint256 indexed epochId, uint256 startTime, uint256 endTime)",
  "event ProposalSubmitted(uint256 indexed epochId, address indexed agent, uint256 feeBps, uint256 curveBeta, uint8 curveMode)",
  "event EpochFinalized(uint256 indexed epochId, address indexed winner, uint256 winnerScore)",
  "event RewardClaimed(uint256 indexed epochId, address indexed winner, uint256 amount)",
] as const;

export const ERC20_ABI = [
  "function balanceOf(address) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
] as const;

export const CURVE_MODES = ["Normal", "Defensive", "VolatilityAdaptive"] as const;

// Fill these from deployment.json or .env.local
export const ADDRESSES = {
  evoPool: process.env.NEXT_PUBLIC_EVOPOOL_ADDRESS || "",
  agentController: process.env.NEXT_PUBLIC_CONTROLLER_ADDRESS || "",
  epochManager: process.env.NEXT_PUBLIC_EPOCH_MANAGER_ADDRESS || "",
  timeLock: process.env.NEXT_PUBLIC_TIMELOCK_ADDRESS || "",
  tokenA: process.env.NEXT_PUBLIC_TOKEN_A_ADDRESS || "",
  tokenB: process.env.NEXT_PUBLIC_TOKEN_B_ADDRESS || "",
};

export const BSC_TESTNET_CHAIN_ID = 97;
export const BSC_TESTNET_RPC = "https://data-seed-prebsc-1-s1.binance.org:8545/";
